-- PostgreSQL version of the script

-- Schema cosco
CREATE SCHEMA IF NOT EXISTS cosco;

-- Table cosco.service
CREATE TABLE IF NOT EXISTS cosco.service (
  CODE_SERVICE VARCHAR(45) PRIMARY KEY,
  NAME_SERVICE VARCHAR(45) NOT NULL
);

-- Table cosco.trade
CREATE TABLE IF NOT EXISTS cosco.trade (
  ID_TRADE INT PRIMARY KEY,
  NAME_TRADE VARCHAR(45)
);

-- Table cosco.vessel
CREATE TABLE IF NOT EXISTS cosco.vessel (
  ID_VESSEL VARCHAR(45) PRIMARY KEY,
  NAME_VESSEL VARCHAR(45) NOT NULL,
  LLOYDS INT NOT NULL,
  FLAG_COUNTRY VARCHAR(45),
  YEAR_BUILT DATE, -- Use DATE instead of YEAR
  CALL_SIGN VARCHAR(20) NOT NULL,
  CODE_SERVICE VARCHAR(45) NOT NULL,
  ID_TRADE INT NOT NULL,
  CONSTRAINT FK_SERVICE FOREIGN KEY (CODE_SERVICE) REFERENCES cosco.service (CODE_SERVICE),
  CONSTRAINT FK_TRADE FOREIGN KEY (ID_TRADE) REFERENCES cosco.trade (ID_TRADE)
);

-- Table cosco.schedule
CREATE TABLE IF NOT EXISTS cosco.schedule (
  ID_SCHEDULE INTEGER PRIMARY KEY,
  loopAbbrv VARCHAR(45) NOT NULL,
  voy VARCHAR(45) NOT NULL,
  portName VARCHAR(45) NOT NULL,
  arrDtlocAct TIMESTAMP,
  depDtlocAct TIMESTAMP,
  arrDtlocCos TIMESTAMP,
  depDtlocCos TIMESTAMP,
  ID_VESSEL VARCHAR(45) NOT NULL,
  CONSTRAINT FK_VESSEL FOREIGN KEY (ID_VESSEL) REFERENCES cosco.vessel (ID_VESSEL)
);
